### ISSUE TITLE
Reports aren't showing forecasts from teams that submit only 1-week forecasts

### ISSUE THREAD

**Issue by sbfnk** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#1020] opened 2021-10-06 12:57 UTC
E.g., in Italy

![image](https://user-images.githubusercontent.com/1156307/136206605-42d43b63-c083-48c8-bd0b-b10861cd4222.png)

Related to 

https://github.com/epiforecasts/scoringutils/issues/136

**Comment by Bisaloo** [comment] 2021-10-06 12:59
Duplicate of #759?

(if so, let's keep this one open since you linked to the relevant scoringutils issue)

**Comment by sbfnk** [comment] 2021-10-06 13:16
Yes, good spot.

**Closed** 2022-07-18 11:25 UTC
